# Generated by Django 5.1.1 on 2024-09-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='inventory',
            new_name='Inventory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='booking_date',
            new_name='BookingDate',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='no_of_guests',
            new_name='No_of_guests',
        ),
    ]
